var langIdxArr = {
	"en": 0,
	"ar": 1,
	"bg": 2,
	"cs": 3,
	"da": 4,
	"de": 5,
	"el": 6,
	"es": 7,
	"et": 8,
	"fa": 9,
	"fi": 10,
	"fr": 11,
	"hr": 12,
	"hu": 13,
	"hy": 14,
	"id": 15,
	"it": 16,
	"ja": 17,
	"ka": 18,
	"ko": 19,
	"lt": 20,
	"lv": 21,
	"ms": 22,
	"nl": 23,
	"no": 24,
	"pl": 25,
	"pt": 26,
	"ru": 27,
	"sk": 28,
	"sr": 29,
	"sv": 30,
	"th": 31,
	"tl": 32,
	"tr": 33,
	"uk": 34,
	"vi": 35,
	"zh": 36,
	"zt": 37,
	"ro": 38,
	"bn": 39,

}

var hyperTexts = {
	"specialFeatureText": ["SPECIAL FEATURE", "ميزة مميزة", "СПЕЦИАЛЕН БОНУС", "SPECIÁLNÍ FUNKCE", "SÆRLIG FUNKTION", "SPEZIAL-FEATURE", "ΕΙΔΙΚΗ ΛΕΙΤΟΥΡΓΙΑ", "FUNCIÓN ESPECIAL", "ERIVOOR", "ویژگی خاص", "ERIKOISTOIMINTO", "FONCTION SPÉCIALE", "POSEBNA ZNAČAJKA", "KÜLÖNLEGES JÁTÉKMÓD", "ՀԱՏՈՒԿ ԳՈՐԾԱՌՈՒՅԹ", "FITUR KHUSUS", "FUNZIONE SPECIALE", "スペシャル機能", "სპეციალური ფუნქცია", "스페셜 기능", "SPECIALI FUNKCIJA", "ĪPAŠA PAPILDSPĒLE", "CIRI ISTIMEWA", "SPECIALE FEATURE", "SPESIELL FUNKSJON", "FUNKCJA SPECJALNA", "MODO ESPECIAL", "СПЕЦИАЛЬНАЯ ФУНКЦИЯ", "ŠPECIÁLNA FUNKCIA", "SPECIJALNA FUNKCIJA", "SPECIALFUNKTION", "ฟีเจอร์พิเศษ", "ESPESYAL NA FEATURE", "ÖZEL ÖZELLİK", "СПЕЦІАЛЬНА ФУНКЦІЯ", "TÍNH NĂNG ĐẶC BIỆT", "特殊功能", "特殊功能", "FUNCTIE SPECIALA", "ফ্রি স্পিন ফিচার"],
	"selectFeatureText": ["Select how you want to play your special feature.", "حدد الكيفية التي تريد لعب الميزة المميزة بها.", "Изберете как да играете специалния бонус.", "Vyberte si, jak chcete hrát svou speciální funkci.", "Vælg, hvordan du vil spille din særlige funktion.", "Wählen Sie, wie Sie Ihr Spezial-Feature spielen möchten.", "Επιλέξτε πώς θέλετε να παίξετε την ειδική λειτουργία σας.", "Seleccione cómo quiere jugar a su función especial.", "Vali, kuidas soovid oma erivooru mängida.", "نحوه اجرای ویژگی خاص خود را انتخاب کنید.", "Valitse miten haluat pelata erikoistoiminnon.", "Choisissez comment vous voulez jouer votre fonction spéciale.", "Odaberite kako želite odigrati posebnu značajku.", "Válassza ki, hogyan szeretné lejátszani a különleges játékmódot.", "Ընտրեք, թե ինչպես եք ցանկանում խաղալ ձեր հատուկ գործառույթը։", "Pilih cara Anda ingin memainkan fitur khusus Anda.", "Seleziona come desideri giocare la tua funzione speciale.", "スペシャル機能をどのようにプレイするかを選択します。", "აირჩიეთ სპეციალური ფუნქციით თამაშის ვარიანტი.", "스페셜 기능 플레이 방법을 선택하세요.", "Pasirinkite, kaip norite paleisti specialiąją funkciją.", "Atlasi, kā vēlies spēlēt savu īpašo papildspēli", "Pilih bagaimana anda ingin bermain ciri istimewa anda.", "Selecteer hoe u uw speciale feature wilt spelen.", "Velg hvordan du vil spille din valgte funksjon.", "Wybierz, jak chcesz rozegrać funkcję specjalną.", "Selecione como quer jogar o seu modo especial.", "Выберите, как вы хотите запустить специальную функцию.", "Vyberte si, ako chcete hrať špeciálnu funkciu.", "Izaberite kako želite da odigrate svoju specijalnu funkciju.", "Välj hur du vill spela din specialfunktion.", "เลือกวิธีที่คุณต้องการเล่นฟีเจอร์พิเศษของคุณ", "Piliin kung paano mo gustong laruin ang iyong espesyal na feature.", "Özel özelliğinizi nasıl oynamak istediğinizi seçin.", "Виберіть, як ви хочете запустити спеціальну функцію.", "Chọn cách bạn muốn chơi tính năng đặc biệt.", "选择特殊功能的玩法。", "選擇特殊功能的玩法。", "Alege cum vrei sa joci functia speciala", "আপনার ফিচারটি আপনি কিভাবে খেলতে চান, তা নির্বাচন করুন"],
	"continueHereText": ["CONTINUE HERE", "تابع هنا", "ПРОДЪЛЖИ ТУК", "POKRAČOVAT ZDE", "FORTSÆT HER", "HIER FORTFAHREN", "ΣΥΝΕΧΙΣΤΕ ΕΔΩ", "CONTINUAR AQUÍ", "JÄTKA SIIN", "از اینجا ادامه دهید", "JATKA TÄÄLLÄ", "CONTINUER ICI", "NASTAVITE OVDJE", "KATTINTSON IDE A FOLYTATÁSHOZ", "ՇԱՐՈՒՆԱԿԵԼ ԱՅՍՏԵՂ", "LANJUTKAN DI SINI", "PROSEGUI QUI", "ここから続ける", "აქ გაგრძელება", "여기서 계속", "TĘSTI ČIA", "TURPINĀT ŠEIT", "TERUSKAN DI SINI", "HIER DOORGAAN", "FORTSETT HER", "KONTYNUUJ TUTAJ", "CONTINUAR AQUI", "ПРОДОЛЖИТЬ ЗДЕСЬ", "POKRAČOVAŤ TU", "NASTAVITE OVDE", "FORTSÄTT HÄR", "ดำเนินการต่อที่นี่", "MAGPATULOY DITO", "BURADA DEVAM ET", "ПРОДОВЖИТИ ТУТ", "TIẾP TỤC TẠI ĐÂY", "此处继续", "此處繼續", "CONTINUA AICI", "এখানে চালিয়ে যান"],
	"playFeatureText": ["PLAY FEATURE IN GAME", "العب الميزة داخل اللعبة", "ИГРАЙ БОНУСА В ИГРАТА", "HRÁT SPECIÁLNÍ FUNKCI VE HŘE", "SPILFUNKTION I SPIL", "FEATURE IM SPIEL SPIELEN", "ΠΑΙΞΤΕ ΤΗ ΛΕΙΤΟΥΡΓΙΑ ΣΤΟ ΠΑΙΧΝΙΔΙ", "JUGAR FUNCIÓN EN EL JUEGO", "MÄNGI ERIVOORU MÄNGUS", "ویژگی را در بازی پخش کنید", "PELAA TOIMINTO PELISSÄ", "JOUER LA FONCTION DANS LE JEU", "ODIGRAJTE ZNAČAJKU U IGRI", "JÁTÉKMÓD LEJÁTSZÁSA A JÁTÉKBAN", "ԽԱՂԱԼ ԳՈՐԾԱՌՈՒՅԹԸ ԽԱՂՈՒՄ", "MAINKAN FITUR DI PERMAINAN", "GIOCA LA FUNZIONE IN GIOCO", "ゲームで機能をプレイ", "ფუნქციის თამაშში გააქტიურება", "게임에서 기능 플레이", "PALEISTI FUNKCIJĄ ŽAIDIME", "SPĒLĒT PAPILDSPĒLI SPĒLĒ", "MAIN CIRI DALAM PERMAINAN", "FEATURE IN GAME SPELEN", "SPILL FUNKSJON I SPILLET", "ROZEGRAJ FUNKCJĘ W GRZE", "JOGAR MODO NO JOGO", "ЗАПУСТИТЬ ФУНКЦИЮ В ИГРЕ", "ODOHRAŤ FUNKCIU V HRE", "IGRAJTE FUNKCIJU U IGRI", "SPELA FUNKTIONEN I SPELET", "เล่นฟีเจอร์ในเกม", "LARUIN ANG FEATURE SA GAME", "ÖZELLİĞİ OYUNDA OYNA", "ЗАПУСТИТИ ФУНКЦІЮ В ГРІ", "CHƠI TÍNH NĂNG TRONG TRÒ CHƠI", "在游戏中开始功能", "在遊戲中開始功能", "VEZI FUNCTIA SPECIALA IN JOC", "গেমে ফিচার খেলুন"],
	"setupText1": ["Hyperplay is superfast autoplay without reels.", "ميزة Hyperplay هي تشغيل تلقائي فائق السرعة بدون بكرات.", "Hyperplay е режим на супербърза автоигра без барабани.", "Hyperplay je velmi rychlá automatická hra bez válců.", "Hyperplay er superhurtigt autospil uden hjul.", "Hyperplay ist ein superschnelles Autospiel ohne Walzen.", "Το Hyperplay αποτελεί υπεργρήγορο αυτόματο παιχνίδι χωρίς κυλίνδρους.", "El Hyperplay es un modo de autojuego super rápido sin rodillos.", "Hyperplay on ülikiire automaatmäng ilma rullikuteta.", "Hyperplay، پخش خودکار فوق سریع بدون حلقه است.", "Hyperplay on supernopea automaattisen pelaamisen toiminto ilman rullia.", "Le mode hyperplay est un mode de jeu automatique super rapide sans rouleaux.", "Hyperplay je superbrza automatska igra bez rola.", "A Hyperplay egy szupergyors automatikus játék tárcsák nélkül.", "Hyperplay-ն առանց պտտանիվների գերարագ ինքնաշխատ խաղ է։", "Hyperplay adalah main otomatis super cepat tanpa reel.", "Hyperplay è una modalità di gioco automatico rapidissima senza rulli.", "Hyperplayはリールのない超高速自動プレイです。", "Hyperplay სუპერსწრაფი ავტომატური თამაშია დოლურების გარეშე.", "Hyperplay는 릴 없이 아주 빠른 자동 플레이입니다.", "Hyperplay yra itin greitas automatinis žaidimas be būgnų.", "Hyperplay ir super ātra autospēle bez spolēm.", "Hyperplay ialah auto main sangat laju tanpa kekili.", "Hyperplay is supersnel autoplay zonder rollen.", "Hyperplay er superraskt autospill uten hjul.", "Hyperplay to niezwykle szybka autogra bez bębnów.", "O Hyperplay é o jogo automático super rápido sem rolos.", "Hyperplay — это сверхбыстрая автоигра без барабанов.", "Hyperplay je superrýchla automatická hra bez valcov.", "Hyperplay je superbrza automatska igra bez bubnjeva.", "Hyperplay är supersnabbt autospel utan hjul. ", "Hyperplay คือการเล่นอัตโนมัติความเร็วสูงโดยไม่ใช้รีล", "Ang Hyperplay ay napakabilis na autoplay na walang reel.", "Hyperplay, makara olmayan süper hızlı otomatik oyundur.", "Hyperplay — це надшвидка автогра без барабанів.", "Hyperplay là chế độ tự động chơi siêu nhanh mà không có các cuộn.", "Hyperplay是不带转轴的超快自动游戏功能。", "Hyperplay是不帶捲軸的超快自動遊戲功能。", "Hyperplay e un mod de joc automat fara role", "Hyperplay হলো রিল ছাড়া অতি দ্রুত অটো-প্লে।"],
	"setupText2": ["Choose your settings and press play to start.", "اختر إعداداتك واضغط على زر التشغيل للبدء.", "Изберете желаните настройки и натиснете „играй“, за да започнете.", "Vyberte si nastavení a stiskněte hrát, abyste začali. ", "Vælg dine indstillinger og tryk på spil for at starte.", "Wählen Sie Ihre Einstellungen und drücken Sie Spielen, um zu starten.", "Επιλέξτε τις ρυθμίσεις σας και πατήστε το Παίξτε για να αρχίσετε.", "Elija su configuración y pulse jugar para comenzar.", "Vali oma seaded ja vajuta mängu alustamiseks mängimisnuppu.", "تنظیمات خود را انتخاب کنید و پخش را فشار دهید تا شروع شود.", "Valitse asetukset ja paina 'pelaa' aloittaaksesi.", "Sélectionnez vos paramètres et appuyez sur jouer pour commencer.", "Odaberite postavke i pritisnite Igraj za početak.", "Válassza ki a beállításait, majd nyomja meg a lejátszást a kezdéshez.", "Ընտրեք ձեր կարգավորումները և սեղմեք խաղալ՝ մեկնարկելու համար։", "Pilih pengaturan Anda dan tekan main untuk memulai.", "Scegli le tue impostazioni e premi gioca per iniziare.", "設定を選択し、プレイを押して開始します。", "აირჩიეთ პარამეტრები და დააჭირეთ დაწყების ღილაკს.", "설정을 선택하고 플레이를 눌러 시작하세요.", "Pasirinkite nustatymus ir paspauskite žaisti, kad pradėtumėte.", "Izvēlies savus iestatījumus un nospied Spēlēt, lai sāktu.", "Pilih tetapan anda dan tekan main untuk bermula.", "Kies uw instellingen en druk op spelen om te starten.", "Velg dine innstillinger og klikk på spill for å starte.", "Wybierz ustawienia i naciśnij Graj, aby rozpocząć.", "Escolha as suas definições e prima jogar para começar.", "Выберите параметры и нажмите кнопку запуска.", "Vyberte si nastavenia a pre spustenie stlačte hrať.", "Izaberite svoja podešavanja i pritisnite Igraj da biste počeli.", "Välj dina inställningar och tryck på spela för att starta.", 'เลือกการตั้งค่าของคุณแล้วกด "เล่น" เพื่อเริ่ม', "Piliin ang iyong mga setting at pindutin ang maglaro para magsimula.", "Ayarlarınızı seçin ve başlamak için oyna tuşuna basın.", "Виберіть параметри та натисніть кнопку запуску.", "Chọn cài đặt của bạn và nhấn vào chơi để bắt đầu.", "选择设置，然后按“开始”以开始游戏。", "選擇設定，然後按「開始」以開始遊戲。", "Alege optiunile si apasa pe butonul de play pentru a incepe", "আপনার সেটিংস নির্বাচন করুন এবং শুরু করতে প্লে চাপুন।"],
	"setupText3": ["You can pause or adjust these anytime.", "يمكنك إيقافها مؤقتًا أو تعديلها في أي وقت.", "Можете да ги поставите на пауза или промените по всяко време.", "Hru můžete kdykoliv pozastavit a upravit nastavení.", "Du kan til enhver tid sætte dem på pause eller justere dem.", "Sie können diese jederzeit pausieren oder anpassen.", "Μπορείτε να κάνετε παύση ή προσαρμογή αυτών οποιαδήποτε στιγμή.", "Puede pausar o ajustarlo en cualquier momento.", "Sa võid igal ajal mängu peatada ja seadeid muuta.", "می‌توانید هرزمان خواستید این موارد را متوقف یا تنظیم کنید.", "Voit pysäyttää tai säätää näitä milloin tahansa.", "Vous pouvez arrêter et ajuster ceux-ci à tout moment.", "Možete ih pauzirati ili prilagoditi kad god želite.", "Ezeket bármikor szüneteltetheti vagy átállíthatja.", "Կարող եք ցանկացած պահի դադարեցնել և փոփոխել այս կարգավորումները։", "Anda bisa menjeda atau menyesuaikan ini kapan saja.", "Puoi mettere in pausa o modificare queste impostazioni in qualsiasi momento.", "これらはいつでも一時停止したり調整したりできます。", "ამის დაპაუზება ან შეცვლა ნებისმიერ დროს შეგიძლიათ.", "언제든지 일시 중지하거나 조정할 수 있습니다.", "Juos bet kada galite pristabdyti arba koreguoti.", "Tu vari to pauzēt vai pielāgot jebkurā brīdī.", "Anda boleh menjeda atau melaraskannya pada bila-bila masa.", "U kunt deze op elk moment pauzeren of aanpassen.", "Du kan når som helst sette disse på pause eller justere dem.", "Możesz wstrzymać lub dostosować ustawienia w dowolnej chwili.", "Pode interromper ou ajustá-las a qualquer altura.", "Вы можете приостанавливать или изменять настройки в любой момент.", "Hru môžete kedykoľvek pozastaviť alebo prispôsobiť.", "Možete da ih pauzirate ili prilagodite u bilo kom trenutku.", "Du kan pausa eller justera dessa när som helst.", "คุณสามารถหยุดชั่วคราวหรือปรับสิ่งเหล่านี้ได้ตลอดเวลา", "Puwede mong i-pause o i-adjust ang mga ito anumang oras.", "Bunları istediğiniz an duraklatabilir veya ayarlayabilirsiniz.", "Ви можете призупиняти або змінювати налаштування в будь-який момент.", "Bạn có thể tạm dừng hoặc điều chỉnh các cài đặt này bất cứ lúc nào.", "您可以随时暂停或进行调整。", "您可以隨時暫停或進行調整。", "Poti pune pauza si sa le schimbi oricand", "আপনি যেকোনো সময় এগুলোতে বিরতি দিতে বা সামঞ্জস্য করতে পারেন।"],
	"anteBetText": ["ANTE BET", "الرهان المسبق", "ЗАЛОГ АНТЕ", "SÁZKA ANTE", "ANTE-INDSATS", "ANTE-EINSATZ", "ΣΤΟΙΧΗΜΑ ΑΝΤΕ", "APUESTA ANTE", "EELPANUS", "پیش شرط", "ALKUPANOS", "MISE D’ANTE", "POČETNI ULOG", "KOCKÁZTATOTT TÉT", "ԱՆՏԵ ԽԱՂԱԴՐՈՒՅՔ", "TARUHAN ANTE", "PUNTATA ANTE", "アンティベット", "ანტე ფსონი", "앤티 벳", "ANTE STATYMAS", "ANTE LIKME", "TARUHAN ANTE", "ANTE-INZET", "ANTE-INNSATS", "ZAKŁAD ANTE", "APOSTA ANTE", "СТАВКА АНТЕ", "ANTE STÁVKA", "ANTE ULOG", "ANTE-INSATS", "ตัวเลือกเดิมพันก่อนเล่น", "TAYA SA ANTE", "ANTE BAHİS", "СТАВКА АНТЕ", "CƯỢC TRƯỚC", "底注", "底注", "MIZA SPECIALA", "অ্যানটি বেট"],
	"stopOnFeatureText": ["STOP ON FEATURE", "توقف عند الميزة", "СТОП ПРИ БОНУС", "ZASTAVIT PŘI SPECIÁLNÍ FUNKCI", "STOP PÅ FUNKTION", "„STOPPEN BEI“-FEATURE", "ΛΕΙΤΟΥΡΓΙΑ ΔΙΑΚΟΠΗΣ", "DETENERSE EN LA FUNCIÓN", "PEATU VOORU VÕITMISEL", "توقف روی ویژگی", "PYSÄYTÄ TOIMINNOLLA", "ARRÊTER LA FONCTION", "ZAUSTAVI U ZNAČAJCI", "MEGÁLLÍTÁS JÁTÉKMÓD ESETÉN", "ԿԱՆԳ ԳՈՐԾԱՌՈՒՅԹԻ ՎՐԱ", "FITUR BERHENTI DI", "FERMATI SULLA FUNZIONE", "機能で停止", "ფუნქციაზე გაჩერება", "기능에서 정지", "STABDYTI ANT FUNKCIJOS", "APTURĒT PAPILDSPĒLI", "BERHENTI PADA CIRI", "STOP OP FEATURE", "STOPP VED FUNKSJON", "ZATRZYMAJ PRZY FUNKCJI", "PARAR NO MODO", "ОСТАНОВИТЬ ПРИ ФУНКЦИИ", "ZASTAVIŤ NA FUNKCII", "ZAUSTAVI NA FUNKCIJI", "STANNA PÅ FUNKTION", "หยุดเมื่อเกิดฟีเจอร์", "HUMINTO SA FEATURE", "ÖZELLİKTE DUR", "ЗУПИНИТИ ПРИ ФУНКЦІЇ", "DỪNG KHI CHẠY TÍNH NĂNG", "停止功能", "停止功能", "OPRESTE LA FUNCTIE SPECIALA", "ফিচারে থামুন"],
	"bet": ["BET", "الرهان", "ЗАЛОГ", "SÁZKA", "INDSATS", "EINSATZ", "ΣΤΟΙΧΗΜΑ", "APUESTA", "PANUS", "شرط", "PANOS", "MISE", "ULOG", "TÉT", "ԽԱՂԱԴՐՈՒՅՔ", "TARUHAN", "PUNTATA", "ベット", "ფსონი", "베팅", "STATYMAS", "LIKME", "TARUHAN", "INZET", "INNSATS", "ZAKŁAD", "APOSTA", "СТАВКА", "STÁVKA", "ULOG", "INSATS", "เดิมพัน", "TAYA", "BAHİS", "Cтавки", "CƯỢC", "赌注", "賭注", "MIZA", "বেট"],
	"totalBet": ["TOTAL BET", "إجمالي الرهان", "ОБЩ ЗАЛОГ", "CELKOVÁ SÁZKA", "SAMLET INDSAT", "GESAMTEINSATZ", "ΣΥΝΟΛΙΚΟ ΣΤΟΙΧΗΜΑ", "APUESTA TOTAL", "KOGUPANUS", "کل شرط", "KOKONAISPANOS", "MISE TOTALE", "UKUPAN ULOG", "ÖSSZES TÉT", "ԸՆԴՀԱՆՈՒՐ ԽԱՂԱԴՐՈՒՅՔ", "TOTAL TARUHAN", "PUNTATA TOTALE", "合計ベット", "მთლიანი ფსონი", "총 베팅", "BENDRAS STATYMAS", "KOPĒJĀ LIKME", "JUMLAH TARUHAN", "TOTALE INZET", "TOTAL INNSATS", "ŁĄCZNY ZAKŁAD", "APOSTA TOTAL", "ОБЩАЯ СТАВКА", "CELKOVÁ STÁVKA", "UKUPAN ULOG", "TOTAL INSATS", "เดิมพันรวม", "KABUUANG TAYA", "TOPLAM BAHİS", "ЗАГАЛЬНА СТАВКА", "TỔNG CƯỢC", "总赌注", "總賭注", "MIZA TOTALA", "মোট বেট"],
	"spin": ["SPIN", "لفة", "ЗАВЪРТАНЕ", "OTOČENÍ", "SPIN", "SPIN", "ΠΕΡΙΣΤΡΟΦΗ", "TIRADA", "KEERUTUS", "چرخش", "PYÖRÄYTYS", "SPINS", "VRTNJA", "PÖRGETÉS", "ՍՊԻՆ", "PUTARAN", "GIRO", "スピン", "დატრიალება", "스핀", "SUKIMAS", "GRIEZIENS", "PUTARAN", "SPIN", "SPINN", "OBRÓT", "RODADA", "СПИН", "TOČIŤ", "SPIN", "SPINN", "สปินที่", "SPIN", "SPİN", "СПІН", "VÒNG QUAY", "旋转", "旋轉", "JOC", "স্পিন"],
	"spins": ["SPINS", "لفات", "ЗАВЪРТАНИЯ", "OTOČENÍ", "SPINS", "SPINS", "ΠΕΡΙΣΤΡΟΦΕΣ ", "TIRADAS", "SPINNE", "چرخش ها", "PYÖRÄYTYSTÄ", "SPINS", "VRTNJE", "PÖRGETÉSEK", "ՍՊԻՆՆԵՐ", "PUTARAN", "GIRI", "スピン", "დატრიალებები", "스핀", "SUKIMAI", "GRIEZIENI", "PUTARAN", "SPINS", "SPINN", "OBROTY", "RODADAS", "СПИНЫ", "TOČENÍA", "SPINOVI", "SPINN", "สปิน", "SPIN", "SPİNLER", "ОБЕРТАННЯ", "VÒNG QUAY", "旋转", "旋轉", "JOCURI", "স্পিনগুলি"],
	"win": ["WIN", "الربح", "ПЕЧАЛБА", "VÝHRA", "GEVINST", "GEWINN", "ΚΕΡΔΙΣTE ", "GANANCIA ", "VÕIT", "برد", "VOITTO", "GAINS", "DOBITAK", "NYERT", "ՇԱՀՈՒՄ", "MENANG", "VINCITA", "勝利", "მოგება", "승리", "LAIMĖJIMAS", "LAIMESTS", "MENANG", "WINST", "VINN", "WYGRAJ", "PRÉMIO", "ВЫИГРЫШ", "VÝHRA", "DOBITAK", "VINN", "ชนะ", "PANALO", "KAZANÇ", "ВИГРАШ", "THẮNG", "奖金", "獎金", "CASTIG", "জয়"],
	"totalWin": ["TOTAL WIN", "الربح الإجمالي", "ОБЩА ПЕЧАЛБА", "CELKOVÁ VÝHRA", "SAMLET GEVINST", "GESAMTGEWINN", "ΣΥΝΟΛΙΚΟ ΚΕΡΔΟΣ", "PREMIO TOTAL", "KOGUVÕIT", "کل برد", "KOKONAISVOITTO", "GAIN TOTAL", "UKUPNI DOBITAK", "ÖSSZES NYEREMÉNY", "ԸՆԴՀԱՆՈՒՐ ՇԱՀՈՒՄ", "TOTAL KEMENANGAN", "VINCITA TOTALE", "勝利の合計", "სულ მოგება", "총 당첨금", "BENDRAS LAIMĖJIMAS", "LAIMESTA KOPSUMMA", "JUMLAH KEMENANGAN", "TOTALE WINST", "TOTAL GEVINST", "ŁĄCZNA WYGRANA", "PRÉMIO TOTAL", "ОБЩИЙ ВЫИГРЫШ", "CELKOVÁ VÝHRA", "UKUPAN DOBITAK", "TOTALVINST", "รางวัลรวม", "KABUUANG PANALO", "TOPLAM KAZANÇ", "ЗАГАЛЬНИЙ ВИГРАШ", "TỔNG TIỀN THẮNG", "总奖金", "總獎金", "CASTIG TOTAL", "মোট জয়"],
	"credit": ["CREDIT", "رصيد", "КРЕДИТ", "KREDIT", "KREDIT", "CREDIT", "ΠΙΣΤΩΣΗ", "CRÉDITO", "KREDIIT", "اعتبار", "KREDIITTI", "CRÉDIT", "IZNOS", "KREDIT", "ԿՐԵԴԻՏ", "KREDIT", "CREDITO", "クレジット", "კრედიტი", "크레딧", "KREDITAS", "KREDĪTS", "KREDIT", "TEGOED", "KREDITT", "KREDYT", "CRÉDITO", "БАЛАНС", "KREDIT", "KREDIT", "KREDIT", "เครดิต", "CREDIT", "KREDİ", "БАЛАНС", "TÍN DỤNG", "筹码", "籌碼", "CREDIT", "ক্রেডিট"],
	"startingCredit": ["STARTING CREDIT", "رصيد البدء", "НАЧАЛЕН КРЕДИТ", "POČÁTEČNÍ KREDIT", "STARTKREDIT", "ANFANGS-CREDIT", "ΕΝΑΡΞΗ ΠΙΣΤΩΣΗΣ", "CRÉDITO INICIAL", "ALGKREDIIT", "اعتبار شروع", "ALOITUSKREDIITTI", "CRÉDIT DE DÉPART", "POČETNI IZNOS", "KEZDŐ KREDIT", "ՄԵԿՆԱՐԿԱՅԻՆ ԿՐԵԴԻՏ", "KREDIT AWAL", "CREDITO INIZIALE", "開始クレジット", "საწყისი კრედიტი", "시작 크레딧", "PRADINIS KREDITAS", "SĀKUMA KREDĪTS", "KREDIT PERMULAAN", "STARTTEGOED", "INNLEDENDE KREDITT", "POCZĄTKOWY KREDYT", "CRÉDITO INICIAL", "НАЧАЛЬНЫЙ БАЛАНС", "POČIATOČNÝ KREDIT", "POČETNI KREDIT", "STARTKREDIT", "เครดิตเริ่มต้น", "CREDIT SA PAGSISIMULA", "BAŞLANGIÇ KREDİSİ", "ПОЧАТКОВИЙ БАЛАНС", "TÍN DỤNG BẮT ĐẦU", "起始筹码", "起始籌碼", "CREDIT INITIAL", "প্রারম্ভিক ক্রেডিট"],
	"playing": ["PLAYING", "جاري اللعب", "ИГРАЕ СЕ", "HRANÍ", "SPILLER", "SPIELT", "ΠΑΙΖΕΙ", "JUGANDO", "MÄNG KÄIB", "در حال پخش", "PELI KÄYNNISSÄ", "EN COURS", "IGRA TRAJE", "LEJÁTSZÁS FOLYAMATBAN", "ԽԱՂ", "BERMAIN", "IN GIOCO", "プレイ中", "თამაში", "플레이 중", "ŽAIDŽIAMA", "SPĒLĒ", "SEDANG BERMAIN", "SPELEN", "SPILLER", "GRA", "A JOGAR", "ИГРАТЬ", "HRANIE", "IGRANJE", "SPELAR", "กำลังเล่น", "NAGLALARO", "OYNANIYOR", "ГРАТИ", "ĐANG CHƠI", "游戏中", "遊戲中", "ACTIV", "খেলছে"],
	"ready": ["READY", "جاهز", "ГОТОВО", "PŘIPRAVENO", "KLAR", "BEREIT", "ΕΤΟΙΜΟ", "LISTO", "VALMIS", "آماده", "VALMIS", "PRÊT·E", "SPREMNO", "KÉSZ", "ՊԱՏՐԱՍՏ", "SIAP", "PRONTO", "準備完了", "მზადაა", "준비", "PARENGTA", "GATAVS", "SEDIA", "KLAAR", "KLAR", "GOTOWE", "PRONTO", "ГОТОВО", "PRIPRAVENÉ", "SPREMNO", "KLAR", "พร้อม", "MAGHANDA", "HAZIR", "ГОТОВО", "SẴN SÀNG", "就绪", "就緒", "PREGATIT", "প্রস্তুত"],
	"nomoney": ["INSUFFICIENT FUNDS", "رصيد غير كافٍ", "НЕДОСТАТЪЧНО СРЕДСТВА", "NEDOSTATEČNÉ FINANČNÍ PROSTŘEDKY", "UTILSTRÆKKELIGE MIDLER", "UNGENÜGENDES GUTHABEN", "ΑΝΕΠΑΡΚΗ ΚΕΦΑΛΑΙΑ", "FONDOS INSUFICIENTES", "EBAPIISAV SALDO", "موجودی کافی نیست", "RIITTÄMÄTTÖMÄT VARAT", "FONDS INSUFFISANTS", "NEDOVOLJNO SREDSTAVA", "NINCS ELEGENDŐ EGYENLEG", "ԱՆԲԱՎԱՐԱՐ ՄԻՋՈՑՆԵՐ", "DANA KURANG", "FONDI INSUFFICIENTI", "資金不足", "თანხა არასაკმარისია", "자금 부족", "NEPAKANKA LĖŠŲ", "NEPIETIEK LĪDZEKĻU", "DANA TIDAK MENCUKUPI", "ONVOLDOENDE SALDO", "UTILSTREKKELIGE MIDLER", "NIEWYSTARCZAJĄCE ŚRODKI", "FUNDOS INSUFICIENTES", "НЕДОСТАТОЧНО СРЕДСТВ", "NEDOSTATOK PROSTRIEDKOV", "NEDOVOLJNA SREDSTVA", "OTILLRÄCKLIGA MEDEL", "เงินทุนไม่พอ", "KULANG ANG PONDO", "YETERSİZ BAKİYE", "НЕДОСТАТНЬО КОШТІВ", "KHÔNG ĐỦ TIỀN", "资金不足", "資金不足", "FONDURI INSUFICIENTE", "ফান্ড অপর্যাপ্ত"],
	"topup": ["To continue, please reduce your bet size or top up your account.", "للمتابعة، يُرجى تخفيض مبلغ رهانك أو شحن حسابك.", "За да продължите, намалете размера на залога или заредете сметката си.", "Chcete-li pokračovat, snižte velikost sázky nebo dobijte svůj účet.", "For at fortsætte skal du reducere din indsats eller indbetale flere penge på din konto.", "Um fortzufahren, verringern Sie bitte Ihren Einsatz oder erhöhen Sie Ihr Kontoguthaben.", "Για να συνεχίσετε, μειώστε το ποσό του στοιχήματός σας ή ανανεώστε τον λογαριασμό σας.", "Para continuar, por favor, reduzca el tamaño de su apuesta o recargue su cuenta.", "Jätkamiseks vähenda palun oma panuse suurust või lisa oma kontole raha.", "برای ادامه، لطفا میزان شرط خود را کم کرده یا حساب خود را شارژ کنید.", "Jatkaaksesi, vähennä panoskokoasi tai tee talletus", "Pour continuer, veuillez réduire le montant de votre mise ou approvisionner votre compte.", "Ako želite nastaviti, smanjite iznos uloga ili nadoplatite račun.", "A folytatáshoz kérjük, csökkentse a tét értékét vagy töltse fel egyenlegét.", "Շարունակելու համար, նվազեցրեք ձեր խաղադրույքը կամ համալրեք ձեր հաշիվը։", "Untuk melanjutkan, kurangi ukuran taruhan Anda atau tambah saldo akun Anda.", "Per proseguire, riduci la dimensione della tua puntata o ricarica il tuo conto.", "続けるには、ベットを減らすか、アカウントに資金を追加してください。", "გასაგრძელებლად შეამცირეთ ფსონის ოდენობა ან შეავსეთ თქვენი ანგარიში.", "계속하려면 베팅 규모를 줄이거나 계정에 입금하세요", "Jei norite tęsti, sumažinkite statymo dydį arba papildykite savo sąskaitą.", "Lai turpinātu, lūdzu, samazini likmes apjomu vai papildini savu kontu.", "Untuk teruskan, sila kurangkan saiz taruhan atau tambah nilai akaun anda.", "Om door te gaan, verlaag uw inzet of voeg saldo toe aan uw account.", "For å fortsette, reduser innsatsen eller fyll på spillekontoen.", "Aby kontynuować, zmniejsz wysokość zakładu lub doładuj swoje konto.", "Para continuar, reduza o valor da sua aposta ou carregue a sua conta.", "Чтобы продолжить, уменьшите размер ставки или пополните счет.", "Pre pokračovanie znížte výšku stávky alebo dobite svoj účet.", "Da biste nastavili, smanjite veličinu uloga ili dopunite svoj nalog.", "För att fortsätta, vänligen minska din insatsstorlek eller fyll på ditt konto.", "หากต้องการดำเนินการต่อ โปรดลดจำนวนเงินเดิมพันของคุณหรือเติมเงินในบัญชี", "Para magpatuloy, pakibawasan ang laki ng iyong taya o magdagdag ng pondo sa iyong account.", "Devam etmek için lütfen bahis miktarını azaltın veya hesabınıza para yatırın.", "Щоб продовжити, зменшіть розмір ставки або поповніть рахунок.", "Để tiếp tục, vui lòng giảm mức cược hoặc nạp tiền vào tài khoản của bạn.", "要继续，请减小赌注大小或为账户充值。", "要繼續，請減小賭注大小或為帳戶充值。", "Pentru a continua, scadeti miza sau alimentati contul", "চালিয়ে যেতে, অনুগ্রহ করে আপনার বেট কমান বা অ্যাকাউন্ট টপ-আপ করুন।"],
	"reconnecting": ["RECONNECTING", "جاري إعادة الاتصال", "СВЪРЗВА СЕ ОТНОВО", "PŘIPOJOVÁNÍ", "GENOPRETTER FORBINDELSE", "VERBINDUNG WIRD WIEDERHERGESTELLT", "ΕΚ ΝΕΟΥ ΣΥΝΔΕΣΗ", "RECONECTANDO", "ÜHENDUSE TAASTAMINE", "در حال اتصال مجدد", "YHDISTETÄÄN UUDELLEEN", "RECONNEXION", "PONOVNO POVEZIVANJE", "ÚJRACSATLAKOZÁS", "ԿԱՊԱԿՑՈՒՄ", "MENGHUBUNGKAN KEMBALI", "RICONNESSIONE IN CORSO", "再接続中", "მიმდინარეობს ხელახლა დაკავშირება", "다시 연결 중", "PRISIJUNGIAMA IŠ NAUJO", "ATJAUNO SAVIENOJUMU", "MENYAMBUNG SEMULA", "VERBINDING WORDT HERSTELD", "GJENOPPRETTER FORBINDELSEN", "PONOWNE ŁĄCZENIE", "A RECONECTAR", "ПОДКЛЮЧЕНИЕ ВОССТАНАВЛИВАЕТСЯ", "PRIPÁJANIE", "PONOVNO POVEZIVANJE", "ÅTERANSLUTNING", "กำลังเชื่อมต่อใหม่", "KUMOKONEKTA ULIT", "YENİDEN BAĞLANIYOR", "ПІДКЛЮЧЕННЯ ВІДНОВЛЮЄТЬСЯ", "ĐANG KẾT NỐI LẠI", "正在重新连接", "正在重新連線", "RECONECTARE", "পুনরায় সংযোগ করা হচ্ছে"],
	"connectionLost": ["CONNECTION LOST", "انقطع الاتصال", "ВРЪЗКАТА СЕ РАЗПАДНА", "ZTRÁTA PŘIPOJENÍ", "FORBINDELSE TABT", "VERBINDUNG ABGEBROCHEN", "ΑΠΩΛΕΙΑ ΣΥΝΔΕΣΗΣ", "CONEXIÓN PERDIDA", "ÜHENDUS KATKES", "ارتباط قطع شد", "YHTEYS MENETETTY", "CONNEXION PERDUE", "PREKINUTA VEZA", "KAPCSOLAT MEGSZAKADT", "ԿԱՊԱԿՑՈՒՄԸ ԲԱՑԱԿԱՅՈՒՄ Է", "KONEKSI HILANG", "CONNESSIONE PERSA", "接続が切断されました", "კავშირი დაიკარგა", "연결 해제됨", "RYŠYS DINGO", "SAVIENOJUMS PĀRTRAUKTS", "SAMBUNGAN TERPUTUS", "VERBINDING VERLOREN", "FORBINDELSE TAPT", "UTRACONO POŁĄCZENIE", "LIGAÇÃO PERDIDA", "СОЕДИНЕНИЕ ПРЕРВАНО", "STRATA PRIPOJENIA", "VEZA JE PREKINUTA", "ANSLUTNING FÖRLORAD", "ขาดการเชื่อมต่อ", "NAWALA ANG KONEKSYON", "BAĞLANTI KAYBOLDU", "ЗВ'ЯЗОК ПЕРЕРВАНО", "MẤT KẾT NỐI", "连接中断", "連線中斷", "CONEXIUNE INTRERUPTA", "সংযোগ বিচ্ছিন্ন"],
	"restart": ["Please restart the game", "يرجى إعادة تشغيل اللعبة", "Рестартирайте играта", "Restartujte prosím hru", "Genstart venligst spillet.", "Bitte starten Sie das Spiel neu", "Επανεκκινήστε το παιχνίδι", "Por favor, reinicie el juego", "Palun taaskäivita mäng", "لطفا بازی را دوباره آغاز کنید", "Käynnistä peli uudelleen", "Veuillez redémarrer le jeu", "Ponovno pokrenite igru", "Kérjük, indítsa újra a játékot", "Վերագործարկեք խաղը", "Tolong mulai ulang permainan", "Riavvia il gioco", "ゲームを再起動してください", "გადატვირთეთ თამაში", "게임을 다시 시작하세요", "Prašome paleisti žaidimą iš naujo", "Lūdzu, restartē spēli", "Sila mulakan semula permainan", "Start de game opnieuw", "Start spillet på nytt", "Uruchom grę ponownie", "Reinicie o jogo", "Пожалуйста, перезапустите игру", "Reštartujte prosím hru", "Ponovo pokrenite igru", "Vänligen starta om spelet", "โปรดรีสตาร์ทเกม", "Paki-restart ang game", "Lütfen oyunu yeniden başlatın", "Будь ласка, перезапустіть гру", "Vui lòng khởi động lại trò chơi", "请重新开始游戏", "請重新開始遊戲", "Va rugam reporniti jocul", "অনুগ্রহ করে গেমটি পুনরায় চালু করুন"],
	"closegame": ["CLOSE GAME", "إغلاق اللعبة", "ЗАТВАРЯНЕ НА ИГРАТА", "ZAVŘÍT HRU", "LUK SPIL", "SPIEL SCHLIESSEN", "ΚΛΕΙΣΙΜΟ ΠΑΙΧΝΙΔΙΟΥ", "CERRAR JUEGO", "SULE MÄNG", "بستن بازی", "SULJE PELI", "FERMER LE JEU", "ZATVORI IGRU", "JÁTÉK BEZÁRÁSA", "ՓԱԿԵԼ ԽԱՂԸ", "TUTUP PERMAINAN", "CHIUDI GIOCO", "ゲームを閉じる", "თამაშის დახურვა", "게임 닫기", "UŽDARYTI ŽAIDIMĄ", "AIZVĒRT SPĒLI", "TUTUP PERMAINAN", "GAME SLUITEN", "LUKK SPILL", "ZAMKNIJ GRĘ", "FECHAR JOGO", "ЗАКРЫТЬ ИГРУ", "ZAVRIEŤ HRU", "ZATVORI IGRU", "STÄNG SPELET", "ปิดเกม", "ISARA ANG GAME", "OYUNU KAPAT", "ЗАКРИТИ ГРУ", "ĐÓNG TRÒ CHƠI", "关闭游戏", "關閉遊戲", "INCHIDE JOCUL", "গেম বন্ধ করুন"],
	"max": ["MAX", "MAX", "МАКС.", "MAX.", "MAKS.", "MAX", "ΜΕΓ.", "MÁX", "MAKS", "MAX", "MAX", "MAX", "MAKS", "MAX.", "MAX", "MAKS", "MAX", "最大", "მაქს.", "최대", "MAKS.", "MAKS.", "MAKS", "MAX", "MAKS", "MAX", "MÁX.", "МАКС.", "MAXIMÁLNE", "MAX", "MAX.", "สูงสุด", "MAX", "MAKS", "МАКС.", "TỐI ĐA", "最大", "最大", "MAX", "সর্বোচ্চ"],
	"paused": ["PAUSED", "متوقف مؤقتًا", "НА ПАУЗА", "POZASTAVENO", "PAUSET", "PAUSIERT", "ΣΕ ΠΑΥΣΗ", "PAUSADO", "PEATATUD", "متوقف شده", "PYSÄYTETTY", "EN PAUSE", "PAUZIRANO", "SZÜNETELTETVE", "ԴԱԴԱՐԵՑՎԱԾ", "DIJEDA", "PAUSA", "一時停止", "დაპაუზდა", "일시 정지됨", "PRISTABDYTA", "PAUZĒTS", "DIJEDA", "GEPAUZEERD", "PAUSE", "WSTRZYMANO", "PAUSA", "ПАУЗА", "POZASTAVENÉ", "PAUZIRANO", "PAUSAD", "หยุดพัก", "NA-PAUSE", "DURAKLATILDI", "ПАУЗА", "ĐÃ TẠM DỪNG", "暂停", "暫停", "PAUZA", "বিরতি দেওয়া হয়েছে"],
	"endCredit": ["END CREDIT", "رصيد النهاية", "КРАЕН КРЕДИТ", "KONEČNÝ KREDIT", "SLUTKREDIT", "ENDGUTHABEN", "ΤΕΛΙΚΗ ΠΙΣΤΩΣΗ", "CRÉDITO FINAL", "LÕPLIK SALDO", "اعتبار پایانی", "KREDIITTEJÄ JÄLJELLÄ", "CRÉDITS FINAUX", "KONAČNI KREDIT", "VÉGSŐ KREDIT", "ՎԵՐՋՆԱԿԱՆ ՄԻԱՎՈՐ", "KREDIT AKHIR", "CREDITO FINALE", "終了クレジット", "დარჩენილი კრედიტი", "종료 크레딧", "BAIGTI KREDITĄ", "BEIGU KREDĪTS", "KREDIT AKHIR", "EINDTEGOED", "SLUTTKREDITT", "KOŃCOWE KREDYTY", "CRÉDITO FINAL", "ОСТАТОК КРЕДИТОВ", "KONEČNÝ KREDIT", "KONAČNI KREDIT", "KREDIT KVAR", "เครดิตตอนจบ", "MATITIRANG CREDIT", "SON KREDİ", "ЗАЛИШОК КРЕДИТІВ", "TÍN DỤNG KẾT THÚC", "最终点数", "最終點數", "CREDIT FINAL", "চূড়ান্ত ক্রেডিট"],
	"newMsg": ["NEW MESSAGE IN GAME", "رسالة جديدة في اللعبة", "НОВО СЪОБЩЕНИЕ В ИГРАТА", "NOVÁ ZPRÁVA VE HŘE", "NY BESKED I SPILLET ", "NEUE NACHRICHT IM SPIEL", "ΝΕΟ ΜΗΝΥΜΑ ΣΤΟ ΠΑΙΧΝΙΔΙ", "MENSAJE NUEVO DEL JUEGO", "UUS SÕNUM MÄNGUS", "پیام جدید در بازی", "UUSI VIESTI PELISSÄ", "NOUVEAU MESSAGE DANS LE JEU", "NOVA PORUKA U IGRI", "ÚJ JÁTÉKBELI ÜZENET", "ՆՈՐ ՀԱՂՈՐԴԱԳՐՈՒԹՅՈՒՆ", "PESAN BARU DI PERMAINAN", "NUOVO MESSAGGIO IN GIOCO", "ゲームの新規メッセージ", "ახალი შეტყობინება თამაშში", "게임 새 메시지", "NAUJA ŽINUTĖ ŽAIDIME", "JAUNS ZIŅOJUMS SPĒLĒ", "MESEJ BAHARU DALAM PERMAINAN", "NIEUW BERICHT IN GAME", "NY MELDING I SPILLET", "NOWA WIADOMOŚĆ W GRZE", "NOVA MENSAGEM NO JOGO", "НОВОЕ СООБЩЕНИЕ В ИГРЕ", "NOVÁ SPRÁVA V HRE", "NOVA PORUKA U IGRI", "NYTT MEDDELANDE I SPELET", "ข้อความใหม่ในเกม", "BAGONG MENSAHE SA LARO", "OYUNDA YENİ MESAJ VAR", "НОВЕ ПОВІДОМЛЕННЯ У ГРІ", "TIN NHẮN MỚI TRONG TRÒ CHƠI", "新游戏消息", "新遊戲消息", "MESAJ NOU IN JOC", "গেমে নতুন বার্তা এসেছে"],
	"close": ["CLOSE", "إغلاق", "ЗАТВАРЯНЕ", "ZAVŘÍT", "LUK", "SCHLIESSEN", "ΚΛΕΙΣΙΜΟ", "CERRAR", "SULE", "بستن", "SULJE", "FERMER", "ZATVORI", "BEZÁRÁS", "ՓԱԿԵԼ", "TUTUP", "CHIUDI", "閉じる", "დახურვა", "닫기", "UŽDARYTI", "AIZVĒRT", "TUTUP", "SLUITEN", "LUKK", "ZAMKNIJ", "FECHAR", "ЗАКРЫТЬ", "ZAVRIEŤ", "ZATVORI", "STÄNG", "ปิด", "ISARA", "KAPAT", "ЗАКРИТИ", "ĐÓNG", "结束", "結束", "INCHIDE", "বন্ধ করুন"],
	"respin": ["RESPIN", "إعادة اللف", "ПОВТОРНО ЗАВЪРТАНЕ", "ZNOVUROZTOČENÍ", "GENSPIN", "RESPIN", "ΕΠΑΝΑΛΗΠΤΙΚΗ ΠΕΡΙΣΤΡΟΦΗ", "RESPIN", "KORDUSKEERUTUS", "چرخش مجدد", "UUDELLEENPYÖRÄYTYS", "RESPIN", "PONOVNA VRTNJA", "ÚJRAPÖRGETÉS", "ՌԵՍՊԻՆ", "RESPIN", "RESPIN", "再スピン", "რესპინი", "리스핀", "PAKARTOTINIS SUKIMAS", "ATKĀRTOTAIS GRIEZIENS", "PUTARAN SEMULA", "RESPIN", "RESPINN", "RESPIN", "NOVA RODADA", "ПОВТОРНЫЙ СПИН", "ZNOVUOTOČENIE", "RESPIN", "OMSPINN", "รีสปิน", "RESPIN", "RESPİN", "ПОВТОРНЕ ОБЕРТАННЯ", "VÒNG QUAY LẠI", "重新旋转", "重新旋轉", "RE-ROTIRE", "আবার স্পিন"],
	"chanceToWin": ["x% Chance to win", "x% فرصة للربح", "x% вероятност за печалба", "x% šance na výhru", "x% chance for at vinde", "Gewinnchance von x%", "x% Πιθανότητα να κερδίσετε", "Posibilidad de ganar x%", "x% võiduvõimalus", "x% شانس برنده شدن", "x% mahdollisuus voittaa", "x% de Chances de gagner", "x% vjerojatnosti za dobitak", "x% esély a nyerésre", "Շահելու x% հնարավորություն", "x% Peluang menang", "x% di probabilità di vincita", "勝利の確率はx%", "x% მოგების შანსი", "x% 당첨 확률", "x% šansas laimėti", "x% iespēja laimēt", "x% Peluang untuk menang", "x% Kans om te winnen", "x% vinnersjanse", "x% szansy na wygraną", "x% Probabilidade de ganhar", "Шанс выиграть: x%", "x% šanca na výhru", "x% šansa za dobitak", "x% chans att vinna", "โอกาสที่จะชนะรางวัล x%", "x% Tiyansang manalo", "x% Kazanma şansı", "Шанс виграти: x%", "x% cơ hội chiến thắng", "x%获胜概率", "x%獲勝概率", "x% Șansă de câștig", "জয়ের সুযোগ x%"],
	"gambleToUpgrade": ["Gamble to upgrade %s", "قامر لترقية %s", "Рискуване за подобряване на %s", "Hazardujte pro vylepšení %s", "Gamble for at opgradere %s", "Zocken, um %s zu verbessern", "Ρισκάρετε για να αναβαθμίσετε το %s", "Arriesgue para mejorar el %s", "Riski, et täiendada %s", "برای ارتقاء %s قمار کنید", "Riskeeraa päivittääksesi to upgrade %s", "Jouez à quitte ou double pour améliorer %s", "Kockajte da nadogradite %s", "Kockáztatás a(z) %s fejlesztéséhez", "Ռիսկի դիմեք և լավարկեք՝ %s", "Bertaruhlah untuk meningkatkan %s", "Rischia per potenziare %s", "ギャンブルして%sをアップグレード", "გარისკეთ და განაახლეთ %s", "갬블하여 %s 업그레이드", "Lošti, kad pagerinti %s", "Riskē, lai uzlabotu %s", "Bertaruh untuk naik taraf %s", "Gok voor verbeteren van %s", "Gamble for å oppgradere %s", "Zaryzykuj, aby ulepszyć %s", "Apostar para melhorar %s", "Рискнуть, чтобы улучшить %s", "Hazardujte pre vylepšenie %s", "Kockajte se da nadogradite %s", "Riskspela för att uppgradera %s", "เสี่ยงพนันเพื่ออัปเกรด %s", "Tumaya para mag-upgrade ng %s", "%s yükseltmek için risk alın", "Ризикнути, щоб поліпшити %s", "Cá cược để nâng cấp %s", "博一博赢以升级%s", "博一博贏以升級%s", "Pariază să crești %s", "%s এ আপগ্রেড করতে জুয়া"],
	"gambleToWin": ["Gamble to win: %s", "قامر لربح: %s", "Рискуване за спечелване: %s", "Hazardujte pro výhru: %s", "Gamble for at vinde: %s", "Zocken, um zu gewinnen: %s", "Ρισκάρετε για να κερδίσετε: %s", "Arriesgue para ganar: %s", "Riski, et võita: %s", "قمار برای برنده شدن: %s", "Riskeeraa voittaaksesi: %s", "Jouez à quitte ou double pour gagner : %s", "Kockajte da osvojite: %s", "Kockáztasson, hogy nyerjen: %s", "Ռիսկի դիմեք, որ շահեք՝ %s", "Bertaruhlah untuk menang: %s", "Rischia per vincere: %s", "ギャンブルして獲得: %s", "გარისკეთ, რომ მოიგოთ: %s", "갬블로 당첨: %s", "Lošti, kad laimėti: %s", "Riskē, lai laimētu: %s", "Bertaruh untuk menang: %s", "Gok voor winnen van: %s", "Gamble for å vinne: %s", "Zaryzykuj, aby wygrać: %s", "Apostar para ganhar: %s", "Рискнуть ради выигрыша: %s", "Hazardujte, aby ste vyhrali: %s", "Kockajte se da osvojite: %s", "Riskspela för att vinna: %s", "เสี่ยงพนันเพื่อชนะรางวัล: %s", "Tumaya para manalo: %s", "Şunu kazanmak için risk alın: %s", "Ризикнути заради виграшу: %s", "Cá cược để giành được: %s", "博一博赢以赢取：%s", "博一博贏以贏取：%s", "Pariază să câștigi: %s", "জয়ের জন্য জুয়া: %s"],
	"gambleFor": ["Gamble for: %s", "قامر من أجل: %s", "Рискуване за: %s", "Hazardujte pro: %s", "Gamble for: %s", "Zocken um: %s", "Ρισκάρετε για: %s", "Arriesgue por: %s", "Riski, et saada: %s", "قمار برای: %s", "Riskeeraa: %s", "Jouez à quitte ou double pour : %s", "Kockajte za: %s", "Ezért kockáztasson: %s", "Ռիսկի դիմեք՝ %s", "Bertaruhlah untuk: %s", "Rischia per: %s", "ギャンブル: %s", "გარისკეთ შემდეგზე: %s", "갬블로 획득 가능: %s", "Lošti dėl: %s", "Riskē par: %s", "Bertaruh untuk: %s", "Gok voor: %s", "Gamble for: %s", "Zaryzykuj dla: %s", "Apostar para: %s", "Рискнуть за: %s", "Hazardujte pre: %s", "Kockajte se za: %s", "Riskspela för: %s", "เสี่ยงพนันเพื่อ: %s", "Tumaya para sa: %s", "Şunun için risk alın: %s", "Ризикнути за: %s", "Cá cược với giá: %s", "博一博赢：%s", "博一博贏：%s", "Pariază pentru: %s", "এর জন্য জুয়া: %s"],
	"collect": ["COLLECT & CONTINUE HERE ", "اجمع وتابع من هنا", "ВЗЕМАНЕ И ПРОДЪЛЖАВАНЕ ТУК", "VYBRAT A POKRAČOVAT ZDE", "INDSAML OG FORTSÆT HER", "SAMMELN UND HIER FORTFAHREN", "ΣΥΛΛΕΞΤΕ ΚΑΙ ΣΥΝΕΧΙΣΤΕ ΕΔΩ", "RECOPILAR Y SEGUIR AQUÍ", "KOGU JA JÄTKA SIIN", "از اینجا جمع آوری کنید و ادامه دهید", "KERÄÄ JA JATKA TÄSTÄ", "RÉCUPÉRER & CONTINUER ICI ", "PRIKUPITE I NASTAVITE OVDJE", "BEGYŰJTÉS ÉS FOLYTATÁS ITT", "ՀԱՎԱՔԵՔ ԵՎ ՇԱՐՈՒՆԱԿԵՔ ԱՅՍՏԵՂ", "KUMPULKAN & LANJUTKAN DI SINI ", "RACCOGLI E CONTINUA QUI", "ここで収集して継続", "შეაგროვეთ და გააგრძელეთ აქ", "여기서 수집하고 계속", "SURINKTI IR TĘSTI ČIA", "SAVĀC UN TURPINI ŠEIT", "KUMPULKAN & TERUSKAN DI SINI", "HIER VERZAMELEN & DOORGAAN", "INNSAMLE OG FORTSETTE HER", "ZBIERZ I KONTYNUUJ TUTAJ", "RECOLHER E CONTINUAR AQUI", "ЗАБРАТЬ И ПРОДОЛЖИТЬ ЗДЕСЬ", "VYBRAŤ A POKRAČOVAŤ TU", "PRIKUPITE I NASTAVITE OVDE", "SAMLA & FORTSÄTT HÄR", "เก็บและดำเนินการต่อที่นี่", "KUMOLEKTA AT MAGPATULOY DITO", "BURADA TOPLAYIN VE DEVAM EDİN", "ЗАБРАТИ І ПРОДОВЖИТИ ТУТ", "THU THẬP & TIẾP TỤC TẠI ĐÂY", "在此处收集并继续", "在此處收集並繼續", "COLECTEAZĂ & CONTINUĂ AICI", "সংগ্রহ করুন ও চালিয়ে যান এখানে"],
	"gambleWarn": ["Gambling can result in no free spins!", "لا يمكن أن تؤدي المقامرة إلى لفات حرة!", "РИСКУВАНЕТО МОЖЕ ДА ДОВЕДЕ ДО ЗАГУБА НА БЕЗПЛАТНИТЕ ЗАВЪРТАНИЯ", "HAZARDOVANÍ MŮŽE ZNAMENAT ŽÁDNÉ DALŠÍ OTOČENÍ ZDARMA", "GAMBLING KAN RESULTERE I INGEN GRATIS SPINS", "GLÜCKSSPIEL KANN GEWINNLOS AUSGEHEN", "ΤΟ ΡΙΣΚΟ ΜΠΟΡΕΙ ΝΑ ΕΧΕΙ ΩΣ ΑΠΟΤΕΛΕΣΜΑ ΚΑΜΙΑ ΔΩΡΕΑΝ ΠΕΡΙΣΤΡΟΦΗ", "RIESGO PUEDE RESULTAR EN NINGUNA TIRADA GRATIS", "RISKIMISE JÄREL VÕID KA TASUTA KEERUTUSTEST ILMA JÄÄDA", "قمار نمی​تواند منجر به چرخش رایگان شود!", "TUPLAAMALLA VOIT MYÖS MENETTÄÄ KAIKKI ILMAISPYÖRÄYTYKSET", "CETTE MISE EN JEU PEUT VOUS FAIRE PERDRE TOUS VOS SPINS GRATUITS", "REZULTAT KOCKANJA MOŽE BITI GUBITAK SVIH BESPLATNIH VRTNJI", "DUPLÁZZÁSSAL LEHET, HOGY NEM NYER SZABADJÁTÉKOT", "ԴՐԱՄԱԽԱՂԸ ՉԻ՛ ԿԱՐՈՂ ԱՌԱՋԱՆԱԼ ԱՆՎՃԱՐ ՊՏՈՒՅՏՆԵՐԻ ԱՐԴՅՈՒՆՔՈՒՄ:", "BERTARUH DAPAT MENGHASILKAN TANPA MEMUTAR GRATIS", "RISCHIARE PUÒ FARTI PERDERE I GIRI GRATIS", "ギャンブルするとフリースピンがない場合もあります", "გარისკვის შედეგად შეიძლება ვერ მიიღო უფასო დატრიალებებები", "갬블로 무료 스핀을 획득하지 못할 수도 있습니다", "LOŠIANT GALIMA PRARASTI LAIMĖTUS NEMOKAMUS SUKIMUS", "BEZMAKSAS GRIEZIENU LAIMESTS NAV GARANTĒTS", "PERTARUHAN MUNGKIN TIDAK MENGHASILKAN PUTARAN PERCUMA", "GOKKEN KAN RESULTEREN IN GEEN FREE SPINS", "GAMBLING KAN RESULTERE I INGEN GRATISSPINN ", "RYZYKO MOŻE SKUTKOWAĆ BRAKIEM DARMOWYCH OBROTÓW", "RISCO PODE RESULTAR NENHUMA RODADA GRÁTIS", "ИГРА МОЖЕТ ПРИВЕСТИ К ПОТЕРИ ВСЕХ БЕСПЛАТНЫХ СПИНОВ", "HAZARDOVANIE MÔŽE ZNAMENAŤ ŽIADNE ĎALŠIE TOČENIA ZADARMO", "ISHOD KOCKANJA MOŽE BITI GUBITAK SVIH BESPLATNIH SPINOVA", "SPEL KAN RESULTERA I INGA GRATISSPINN", "การเสี่ยงเดิมพันอาจทำให้เสียสิทธิ์ฟรีสปินทั้งหมดไป", "ANG PAGTATAYA AY MAAARING MAGRESULTA SA WALANG MGA FREE SPIN!", "BAHİS FREESPİN OLMADAN DA SONUÇLANABİLİR", "В РЕЗУЛЬТАТІ РИЗИКОВАНОЇ ГРИ Є ЙМОВІРНІСТЬ ВТРАТИТИ БЕЗКОШТОВНІ ОБЕРТАННЯ", "VIỆC CÁ CƯỢC CÓ THỂ KHIẾN BẠN MẤT TOÀN BỘ VÒNG QUAY MIỄN PHÍ", "博一博也可能不会赢得免费旋转", "博一博也可能不會贏得免費旋轉", "PARIEREA POATE REZULTA ÎN PIERDEREA ROTIRILOR GRATUITE", "জুয়া খেললে কোনো ফ্রি স্পিন নাও থাকতে পারে!"],
}

hyperTexts.specialFeatureText2 = ["FREE SPINS FEATURE", "ميزة اللفات المجانية", "БОНУС „БЕЗПЛАТНИ ЗАВЪРТАНИЯ”", "SPECIÁLNÍ FUNKCE S ROZTOČENÍMI ZDARMA", "GRATIS SPINS-FUNKTION", "GRATISDREHUNGEN", "ΛΕΙΤΟΥΡΓΙΑ ΔΩΡΕΑΝ ΠΕΡΙΣΤΡΟΦΩΝ", "FUNCIÓN DE TIRADAS GRATIS", "TASUTA KEERUTUSTE VOOR", "ویژگی چرخش رایگان", "ILMAISPYÖRÄYTYSTOIMINTO", "FONCTION SPINS GRATUITS", "ZNAČAJKA BESPLATNE VRTNJE", "INGYENES PÖRGETÉS FUNKCIÓ", "ԱՆՎՃԱՐ ՊՏՈՒՅՏՆԵՐ ԳՈՐԾԱՌՈՒՅԹ", "FITUR PUTARAN GRATIS", "FUNZIONE GIRI GRATIS", "フリースピン機能", "უფასო დატრიალებების ფუნქცია", "무료 스핀 기능", "NEMOKAMŲ SUKIMŲ FUNKCIJA", "BEZMAKSAS GRIEZIENU PAPILDSPĒLE", "CIRI PUTARAN PERCUMA", "GRATIS SPINS FEATURE", "GRATISSPINN FUNKSJON", "FUNKCJA DARMOWYCH OBROTÓW", "MODO RODADAS GRÁTIS", "БОНУСНЫЙ РАУНД БЕСПЛАТНЫХ СПИНОВ", "FUNKCIA TOČENÍ ZADARMO", "FUNKCIJA BESPLATNIH SPINOVA", "GRATISSPINN-FUNKTIONEN", "ฟีเจอร์ฟรีสปิน", "FREE SPINS FEATURE", "FREESPİN ÖZELLİĞİ", "БОНУСНИЙ РАУНД «БЕЗКОШТОВНІ ОБЕРТАННЯ»", "TÍNH NĂNG VÒNG QUAY MIỄN PHÍ", "免费旋转功能", "免費旋轉功能", "FUNCTIE SPECIALA", "ফ্রি স্পিন ফিচার"];
hyperTexts.selectFeatureText2 = ["Select how you want to play your feature", "حدد الطريقة التي تريد بها تشغيل الميزة الخاصة بك", "Изберете как да играете бонуса", "Vyberte, jak chcete hrát svou speciální funkci", "Vælg, hvordan du vil spille din funktion", "Wählen Sie, wie Sie das Feature spielen möchten", "Επιλέξτε πώς θέλετε να παίξετε τη λειτουργία σας", "Seleccione cómo quiere jugar su función", "Vali, kuidas soovid vooru mängida", "انتخاب کنید که چگونه می خواهید ویژگی خود را بازی کنید", "Valitse, miten haluat pelata toiminnon", "CHOISISSEZ COMMENT VOUS SOUHAITEZ JOUER VOTRE FONCTION", "Odaberite kako želite odigrati značajku", "Válassza ki, hogyan szeretné lejátszani a funkcióját.", "Ընտրեք, թե ինչպես եք ցանկանում խաղալ գործառույթը", "Pilih cara Anda ingin memainkan fitur Anda", "Seleziona come vuoi giocare la tua funzione", "機能をどのようにプレイしたいか選択してください", "აირჩიეთ, როგორ გსურთ ფუნქციის თამაში", "기능을 플레이할 방식을 선택하세요", "Pasirinkite, kaip norite žaisti savo funkciją", "Izvēlies, kā vēlies spēlēt savu papildspēli", "Pilih cara anda mahu mainkan ciri anda", "Selecteer hoe u uw feature wilt spelen", "Velg hvordan du vil spille funksjonen din", "Wybierz, jak chcesz rozegrać funkcję", "Selecione como deseja jogar o seu modo", "Выберите, как вы хотите играть функцию", "Vyberte si, ako chcete hrať svoju funkciu", "Izaberite kako želite da odigrate funkciju", "Välj hur du vill spela din funktion", "เลือกวิธีที่คุณต้องการเล่นฟีเจอร์ของคุณ", "Piliin kung paano mo gustong laruin ang iyong feature", "Özelliğinizi nasıl oynamak istediğinizi seçin", "Виберіть, як ви хочете грати функцію", "Chọn cách bạn muốn chơi tính năng của mình", "选择您想要的功能玩法", "選擇您想要的功能玩法", "Alege cum vrei sa joci functia speciala", "আপনার ফিচারটি আপনি কিভাবে খেলতে চান, তা নির্বাচন করুন"];

var noTranslation = {
	//"template": "x"
	"startingMultiplier": "%x STARTING MULTIPLIER",
}

var addNoTranslation = function() {
	for (var k in noTranslation) {
		hyperTexts[k] = [];
		for (var i in langIdxArr)
			hyperTexts[k].push(noTranslation[k]);
	}
}

var HPInit = function() {
	addNoTranslation();

	if (IsRequired("APBR")) {
		var lang = window["UHT_GAME_CONFIG"]["LANGUAGE"];
		if (lang == "en")
			hyperTexts.APBR = "TOTAL: {0} IN {1} SPINS";
		else if (lang == "pt")
			hyperTexts.APBR = "TOTAL: {0} EM {1} RODADAS"
	}
}

HPInit();

var HPFUNC = {};
var HPVARS = {};
HPVARS.logoH = "min(80%, 9em)"
HPVARS.logoW = "65%";
HPVARS.LogoStyle = "";
HPVARS.useFoxForSpinResponse = false;
HPVARS.hasManualSelection = false;
HPVARS.fsItems = "pickableOptions";
HPVARS.FSBG_ScriptName = "FSOptions";
HPVARS.FSBG_ShowMethod = "InitOptions";
HPVARS.FSBG_OnResponseMethod = "OnResponseReceived";
HPVARS.hooksOnFSLabelsConfigured = false;
HPVARS.FSBG_onShowEv = Vars.Evt_CodeToData_ShowFSBGPick;
HPVARS.FSBG_onResponseEv = Vars.Evt_FromServer_ResponseFSBGPick;

HPVARS.winColor = "#2AC814";
HPVARS.loseColor = "#FF2020";

HPVARS.fsRadiusH = 1;
HPVARS.fsRadiusW = 2.18;

HPVARS.fsManualOptH = 11.75;
HPVARS.fsManualOptW = 25.55;
HPVARS.rowGapH = 1.5;
HPVARS.rowGapW = 3.2;

HPVARS.fsOptH = 4.7;
HPVARS.fsOptW = 10.22;
HPVARS.FSOptPercent = 0.75;
HPVARS.fsInnerStyle = "";

HPVARS.customRestoreOverrides = function() {}
;
HPVARS.customInitOverrides = function() {}
;

HPVARS.callFinalizeDisplayedWin = true;
HPVARS.lastTumbleIsZero = true;

var canShowBonus = function(bonusGame) {
	return true;
}

HPFUNC.getBetLevelOptions = function() {
	if (!HPVARS.betLevelManager)
		return;

	HPVARS.betLevelOptions = HPVARS.betLevelManager.betLevelOptions;
}

HPFUNC.extraConditionsMetBeforeRoundEnd = function() {
	return true;
}

HPFUNC.onExtraConditionsChanged = function() {}

var injectTrigger = function(component, method, func, param) {
	var o_method = component[method];
	if (o_method == undefined)
		return;

	component[method] = function() {
		o_method.apply(this, arguments);
		func(component, param);
	}
}

//use eg: injectTrigger(comp, "OnEnable", revealItem, index);
